packages:
  # specify a package in a direct subdir of the root
  - 'client'
  - 'server'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
